navikt/familie-dokument

src/main/kotlin/no/nav/familie/dokument/config/ApplicationConfig.kt, src/main/kotlin/no/nav/familie/dokument/storage/OvergangstonadController.kt, src/main/kotlin/no/nav/familie/dokument/storage/Storage.kt, src/main/kotlin/no/nav/familie/dokument/storage/StorageController.kt, src/main/kotlin/no/nav/familie/dokument/storage/attachment/AttachmentStorage.kt, src/main/kotlin/no/nav/familie/dokument/storage/encryption/EncryptedStorage.kt, src/main/kotlin/no/nav/familie/dokument/storage/mellomlager/MellomLagerService.kt, src/main/kotlin/no/nav/familie/dokument/storage/s3/S3Storage.kt, src/main/resources/application-dev.yaml, src/test/kotlin/no/nav/familie/dokument/DevLauncher.kt, src/test/kotlin/no/nav/familie/dokument/config/CORSResponseFilter.kt, src/test/kotlin/no/nav/familie/dokument/config/CorsProperties.kt, src/test/kotlin/no/nav/familie/dokument/config/TestStorageConfiguration.kt, src/test/kotlin/no/nav/familie/dokument/storage/OvergangstonadControllerTest.kt, src/test/kotlin/no/nav/familie/dokument/storage/attachment/AttachmentStorageTest.kt, src/test/kotlin/no/nav/familie/dokument/storage/mellomlager/MellomlagerServiceTest.kt, src/test/kotlin/no/nav/familie/dokument/storage/s3/S3StorageTest.kt
Laget oppsett for å kunne mellomlagre søknad om overgangsstønad.
=> Feature/mellomlagre overgangsstønad

.deploy/naiserator.yaml, .github/workflows/build-dev.yml, src/main/resources/application-preprod.yaml, src/main/resources/application.yaml
Ny applikasjon lagt til. Skal brukes til å lage en "ef-sak-blankett".
=> Legg til familie-ef-blankett

.deploy/naiserator.yaml
https://nav-it.slack.com/archives/GREQVPXHS/p1622718167025900
https://doc.nais.io/nais-application/ingress/
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
=> Legger til ingress parametrer for å overstyre default grense på 1mb

.github/dependabot.yml
Må ha med en PAT for att det skal virke
=> Oppdaterer dependabot settings

.deploy/naiserator.yaml
Trengs når familie-ef-søknad-api flyttes til GCP
Edit: Hvis det ikke er sånn att vi skal hente vedlegg fra mottak i stedet..
=> Lagt till ef-søknad-api i apper som skal kunne kalle på familie-dokument

.deploy/dev-gcp.json, .deploy/naiserator.yaml, .deploy/prod-gcp.json
Familie-ef-soknad-api finnes allerede, men det er utifra att appen finnes i GCP (som den ikke gjør ennå)
=> familie-ef-soknad-api skal få kalle på familie-dokument med tokenx

src/main/kotlin/no/nav/familie/dokument/pdf/PdfService.kt, src/main/kotlin/no/nav/familie/dokument/storage/StorageController.kt, src/test/kotlin/no/nav/familie/dokument/config/TestStorageConfiguration.kt, src/test/kotlin/no/nav/familie/dokument/storage/StorageControllerTest.kt, src/test/kotlin/no/nav/familie/dokument/storage/integrationTest/StorageControllerIntegrasionTest.kt
Co-authored-by: Charlie Midtlyng <charlie.midtlyng@nav.no>
=> Skal ha et endepunkt for å slå sammen en liste av innsendte dokumenter.

src/main/kotlin/no/nav/familie/dokument/ApiExceptionHandler.kt, src/main/kotlin/no/nav/familie/dokument/ApiExceptions.kt, src/main/kotlin/no/nav/familie/dokument/virusscan/VirusScanService.kt, src/test/kotlin/no/nav/familie/dokument/virusscan/VirusScanServiceTest.kt
https://nav-it.slack.com/archives/G012YEK9YQ1/p1643111800100800
=> Kaster bad request vid virus-treff og logger warning i stedet for error

pom.xml, src/main/kotlin/no/nav/familie/dokument/storage/Extensions.kt, src/test/kotlin/no/nav/familie/dokument/config/IntegrationTestConfig.kt, src/test/kotlin/no/nav/familie/dokument/storage/HentFnrTest.kt, src/test/kotlin/no/nav/familie/dokument/storage/StonadControllerTest.kt, src/test/kotlin/no/nav/familie/dokument/storage/StorageControllerTest.kt, src/test/kotlin/no/nav/familie/dokument/storage/integrationTest/StonadControllerIntegrasionTest.kt, src/test/kotlin/no/nav/familie/dokument/storage/integrationTest/StorageControllerIntegrasionTest.kt, src/test/kotlin/no/nav/familie/dokument/testutils/ExtensionMockUtil.kt
https://nav-it.slack.com/archives/CJN0STWB0/p1645098679037819
=> Idporten støtte for pid

src/main/kotlin/no/nav/familie/dokument/storage/StonadController.kt, src/main/resources/application-preprod.yaml
Legger til kontantstøtte over søknader som får lov å bruke mellomlagring
=> Legg til kontantstøtte

.deploy/nais-dev.yaml, .deploy/nais-prod.yaml
Vi flytter familie-ba-mottak til GCP, og bytter samtidig navn til familie-baks-mottak.
=> Tea 9765 gi baks mottak tilgang

.deploy/nais-dev.yaml, .deploy/nais-prod.yaml, src/main/resources/application-preprod.yaml, src/main/resources/application.yaml
Familie-baks-mottak ligger nå i GCP og har tatt over ansvaret for familie-ba-mottak.
=> Tea-9958_fjern_ba_mottak

pom.xml
Fjerner xalan slik som vi har gjort i familie-tilbake
https://github.com/navikt/familie-tilbake/pull/952/files
=> Fjern utrygg transitiv avhengighet

src/main/kotlin/no/nav/familie/dokument/storage/attachment/FlattenPdfService.kt
Må kalle på `.close` på PODocument som `.use` gjør automatisk, litt som try with resource
=> Bruker use for å lukke PODocument automatisk

.deploy/nais-dev.yaml, .deploy/nais-prod.yaml, src/main/kotlin/no/nav/familie/dokument/storage/StonadController.kt, src/main/kotlin/no/nav/familie/dokument/storage/StorageController.kt, src/main/resources/application-e2e.yaml, src/main/resources/application-preprod.yaml, src/main/resources/application.yaml, src/test/kotlin/no/nav/familie/dokument/ApiFeilIntegrationTest.kt, src/test/resources/application-local.yaml
Må testes i preprod av både EF, BA og KS. 
Mellomlagring av søknad og innsending av dokumentasjon.
=> Skal fjerne siste rest av loginservice og selvbetjening-token

.deploy/nais-dev.yaml
Skal generere pdf i første omgang og senere laste opp vedlegg
=> Tilleggsstønader ønsker tilgang til å kunne kalle på dokument

.deploy/nais-dev.yaml, .deploy/nais-prod.yaml
Tilleggsstønader vil å kalle på `familie-dokument` for genering av pdf fra html.
=> ✨ Tilleggsstønader apper skal få kalle på familie-dokument

src/main/kotlin/no/nav/familie/dokument/storage/StorageController.kt, src/test/kotlin/no/nav/familie/dokument/storage/integrationTest/StorageControllerIntegrasionTest.kt
Vi i tillegg tenkte vi skulle bruke familie-dokument for opplasting av vedlegg nå, men at vi kanskje burde vurdere om vi faktiskt burde gjøre det sammen med dere.. 
Har testet å sende inn søknad for OS etter endringene
=> Endepunkt for å hente vedlegg uten å pakke inn det i Ressurs

.deploy/nais-dev.yaml, .deploy/nais-prod.yaml
Deploy vil ikke fungere etter 18. desember uten denne endringen
=> Skal ha gyldig nais-template

.deploy/nais-dev.yaml, .deploy/nais-prod.yaml
Må være i henhold til nais-kontrakten:
https://doc.nais.io/nais-application/example/
=> Fix lifecycle issues

.deploy/nais-dev.yaml, .deploy/nais-prod.yaml
=> Reduser cpu request

.github/dependabot.yml, .github/workflows/build-and-deploy-dev.yml, .github/workflows/build-and-deploy-prod.yml, .github/workflows/build-dev.yml
💰 Hva forsøker du å løse i denne PR'en
Ta i bruk ratchet og dependabot for github actions. Som vil gi oss up-to-date versjoner av workflows vi bruker. Vi lærte i tech-prat at å lene seg på versjonnummer alene utgir en sikkerhetsrisiko.
=> Pin actions med ratchet

.github/workflows/scan-vulnerabilities.yaml
Workflow for å scanne etter sårbarheter i repo.
=> Legg til ny workflow: "Scan vulnerabilities"

pom.xml
Reverts navikt/familie-dokument#550
=> Revert "Bump the all-dependencies group across 1 directory with 9 updates"
